CREATE TABLE "CLIENTES" (
	"END_CLI"	TEXT NOT NULL,
	"ID"	INTEGER NOT NULL,
	"NOME_CLI"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);

CREATE TABLE "ITENS_NOTAFISCAL" (
	"ID"	INTEGER NOT NULL,
	"QTD"	INTEGER NOT NULL,
	"VALOR"	INTEGER NOT NULL,
	"NF_ID"	INTEGER NOT NULL,
	"PRO_ID"	INTEGER NOT NULL,
	FOREIGN KEY("NF_ID") REFERENCES "NOTAS_FISCAIS"("ID"),
	FOREIGN KEY("PRO_ID") REFERENCES "PRODUTOS"("ID"),
	PRIMARY KEY("ID" AUTOINCREMENT)
  );

CREATE TABLE "VENDEDORES" (
	"ID"	INTEGER NOT NULL,
	"NOME_VEND"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);

CREATE TABLE "NOTAS_FISCAIS" (
	"ID"	INTEGER NOT NULL,
	"CLI_ID"	INTEGER NOT NULL,
	"VEND_ID"	INTEGER NOT NULL,
	"NUM_NF"	INTEGER NOT NULL,
	"SERIE_NF"	TEXT NOT NULL,
	FOREIGN KEY("CLI_ID") REFERENCES "CLIENTES"("ID"),
	PRIMARY KEY("ID" AUTOINCREMENT)
);

CREATE TABLE "PRODUTOS" (
	"ID"	INTEGER NOT NULL,
	"NOME_PROD"	INTEGER NOT NULL,
	"PRECO_UNIC"	INTEGER NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);

